version: "3.7"
services:
  db:
    image: postgres:14
    container_name: nestjs-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - nestjs_postgres:/var/lib/postgresql/data

    logging:
      options:
        max-size: "10k"
        max-file: "5"

volumes:
  nestjs_postgres: